#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

Color_Off='\033[0m'

BRed='\033[1;31m'         # Red
BGreen='\033[1;32m'       # Green
BYellow='\033[1;33m'      # Yellow
BBlue='\033[1;34m'        # Blue
BPurple='\033[1;35m'      # Purple
BCyan='\033[1;36m'        # Cyan
BWhite='\033[1;37m'       # White

# Process Start
echo -e "\n${BCyan} *** Executing 'pre-commit' Hook *** ${Color_Off}"

# Prettier
echo -e "\n${BYellow} === Prettier Process Started === ${Color_Off}"
npm run prettier

# Linting
echo -e "\n${BYellow} === Linting Process Started === ${Color_Off}"
npm run lint

# Process Completed
echo "\n${BCyan} *** 'pre-commit' Hook Completed *** ${Color_Off}\n"